---
- name: Install Mesosphere (Zookeeper, Mesos-master, Marathon, Chronos)
  apt: pkg={{ item }} state=latest
    with_items:
      - mesosphere
      - ntp

# used for leader election amongst masters
- name: Set ZooKeeper URL
  copy:
    content: "{{zookeeper_url}}/mesos"
    dest: /etc/mesos/zk
    mode: 0644
  sudo: yes

 Tasks for Master nodes
- name: Disable the Mesos Slave service
  copy:
     content: "manual"
     dest: /etc/init/mesos-slave.override
     mode: 0644
  sudo: yes

- name: Set Mesos Master hostname
  copy:
    content: "{{mesos_local_address}}"
    dest: /etc/mesos-master/hostname
    mode: 0644
  sudo: yes


- name: Set Mesos Master ip
  copy:
    content: "{{mesos_local_address}}"
    dest: /etc/mesos-master/ip
    mode: 0644
  sudo: yes

# The Mesos quorum value is based on the number of Mesos Masters. Take the
# number of masters, divide by 2, and round-up to nearest integer. For example,
# if there are 1 or 2 masters the quorum count is 1. If there are 3 or 4
# masters then the quorum count is 2. For 5 or 6 masters it's 3 and so on.

- name: Set Mesos Master quorum count
  template: src=quorum.j2 dest=/etc/mesos-master/quorum mode=0644
  sudo: yes

- name: Set Mesos Master Cluster name
  copy:
    content: "{{mesos_cluster_name}}"
    dest: /etc/mesos-master/cluster
    mode: 0644
  sudo: yes
  notify:
    - Start mesos-master

