---
- name: Install Mesosphere (Zookeeper, Mesos-master, Marathon, Chronos)
  apt: pkg={{ item }}
  with_items:
    - mesosphere
    - ntp
  sudo: yes

# used for leader election amongst masters
- name: Set ZooKeeper URL for mesos
  copy:
    content: "{{zookeeper_url}}/mesos"
    dest: /etc/mesos/zk
    mode: 0644
  sudo: yes

- name: Set ZooKeeperID
  copy:
    content: "{{zoo_id}}"
    dest: /etc/zookeeper/conf/myid
    mode: 0644
  sudo: yes

- name: Create zookeeper config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  sudo: yes

# Tasks for Mesos Master nodes
- name: Set Mesos Master hostname
  copy:
    content: "{{ansible_eth1.ipv4.address}}"
    dest: /etc/mesos-master/hostname
    mode: 0644
  sudo: yes

- name: Set Mesos Master ip
  copy:
    content: "{{ansible_eth1.ipv4.address}}"
    dest: /etc/mesos-master/ip
    mode: 0644
  sudo: yes

- name: Set Mesos Master quorum count
  copy:
    content: "{{mesos_quorum}}"
    dest: /etc/mesos-master/quorum
    mode: 0644
  sudo: yes

- name: Set Mesos Master Cluster name
  copy:
    content: "{{mesos_cluster_name}}"
    dest: /etc/mesos-master/cluster
    mode: 0644
  sudo: yes

# Tasks to Configure Marathon on the Master Servers
- name: create the marathon conf directory
  shell: sudo mkdir -p /etc/marathon/conf

- name: Copy Mesos hostname to marathon conf
  shell: sudo cp /etc/mesos-master/hostname /etc/marathon/conf

- name: Copy ZK to Merathon conf
  shell: sudo cp /etc/mesos/zk /etc/marathon/conf/master

- name: Set ZooKeeper address
  copy:
    content: "{{zookeeper_url}}/marathon"
    dest: /etc/marathon/conf/zk
    mode: 0644
  sudo: yes

#Configure Service Init Rules and Restart Services
- name: Disable the Mesos Slave service
  copy:
    content: "manual"
    dest: /etc/init/mesos-slave.override
    mode: 0644
  sudo: yes
  notify:
    - Stop mesos-slave
    - Start mesos-master
    - Start zookeeper
    - Start marathon
    - Start chronos
