
zookeeper_servers: "{{ groups['master_nodes'] }}"
mesos_quorum: "{{ ((groups['master_nodes']|length) // 2) + 1 }}"
mesos_quorum2L": "{{ ( groups.master_nodes|count / 2) | round(0, 'ceil') | int }}"
mesos_cluster_name: "Mesos_Cluster"
mesos_ip: "{{ansible_default_ipv4.address}}"
mesos_hostname: "{{ inventory_hostname }}"
zookeeper_client_port: "2181"
zookeeper_hostnames: "{{ mesos_hostname }}:{{ zookeeper_client_port }}"
mesos_zookeeper_masters: "zk://{{ zookeeper_hostnames }}/mesos" 
mesos_local_address: "{{ansible_eth0.ipv4.address}}"
zookeeper_url: "zk://{{ groups.zookeepers | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}"
zookeeper_leader_port: "2888"
zookeeper_election_port: "3888"
