---
# handlers file for mesos
- name: Start mesos-master
  service: name=mesos-master state=restarted
  sudo: yes

- name: Stop mesos-slave
  service: name=mesos-slave state=stopped
  sudo: yes

- name: Start zookeeper
  service: name=zookeeper state=restarted
  sudo: yes

- name: Start marathon
  service: name=marathon state=started
  sudo: yes

- name: Start chronos
  service: name=chronos state=started
  sudo: yes
